sudo: requiered
language: node_js
services:
   - docker
node_js:
   - '4.2'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
  - 'gem install sass'
  - 'gem install compass'
deploy:
  skip_cleanup: true
after_script:
  - docker build -t cheztone/cheztone-frontend .
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" $DOCKER_REPOSITORY;
      docker push cheztone/cheztone-frontend;
      fi